apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  loadBalancerSourceRanges:
  - 10.0.2.0/24  # Application Gateway subnet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to NGINX on AKS</title>
        <style>
            body {
                width: 35em;
                margin: 0 auto;
                font-family: Tahoma, Verdana, Arial, sans-serif;
                background-color: #f0f0f0;
                padding: 20px;
            }
            .container {
                background-color: white;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }
            h1 {
                color: #2c3e50;
            }
            .info {
                background-color: #e8f4fd;
                padding: 15px;
                border-radius: 5px;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to NGINX on Azure Kubernetes Service (AKS)!</h1>
            <p>If you can see this page, the NGINX web server is successfully installed and working through Azure Application Gateway.</p>
            
            <div class="info">
                <strong>Architecture:</strong>
                <ul>
                    <li>Azure Application Gateway (Frontend)</li>
                    <li>Azure Kubernetes Service (AKS)</li>
                    <li>NGINX Deployment (Backend)</li>
                </ul>
            </div>
            
            <p>This deployment demonstrates:</p>
            <ul>
                <li>Bicep infrastructure as code</li>
                <li>Modular architecture with separate VNet subnets</li>
                <li>Application Gateway routing to AKS services</li>
                <li>Load balancing across multiple NGINX pods</li>
            </ul>
            
            <p><em>Thank you for using Azure!</em></p>
        </div>
    </body>
    </html>
