apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: windows-sample
  template:
    metadata:
      labels:
        app: windows-sample
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: windows-sample-container
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp-windowsservercore-ltsc2022
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: windows-sample-service
spec:
  type: LoadBalancer
  selector:
    app: windows-sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80