apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sampleapp
  name: sampleapp
  namespace: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  strategy: {}
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - image: jkacrsimpledemo.azurecr.io/sampleapp:0.1
        name: sampleapp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
