apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: sampleapp-svc
  namespace: sampleapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sampleapp
  sessionAffinity: None

