apiVersion: v1
kind: Namespace
metadata:
  name: externalapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: externalapi
  name: externalapi
  namespace: externalapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: externalapi
  strategy: {}
  template:
    metadata:
      labels:
        app: externalapi
    spec:
      containers:
      - image: jkacrsimpledemo.azurecr.io/sampleapp:0.1
        name: externalapi
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        agentpool: "apps"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: externalapi
  name: externalapi-svc
  namespace: externalapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: externalapi
  sessionAffinity: None

