apiVersion: v1
kind: Namespace
metadata:
  name: weatherapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weatherapi
  name: weatherapi
  namespace: weatherapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapi
  strategy: {}
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - image: jkacrsimpledemo.azurecr.io/sampleapp:0.3
        name: weatherapi
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        agentpool: "apps"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherapi
  name: weatherapi-svc
  namespace: weatherapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: weatherapi
  sessionAffinity: None

