apiVersion: v1
kind: Pod
metadata:
  name: azurefile-test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: azurefile
      mountPath: "/mnt/azure"
  volumes:
  - name: azurefile
    persistentVolumeClaim:
      claimName: azurefile-pvc
