apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: "rg-aksstorage-demo#mystorageaccount13296#demo" # Replace with your values
    readOnly: false
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
